### PR TITLE
Add Database Models

### PR DESCRIPTION
**Pull request by wuryantoAji**
Adding database model while also fixing a bit of the init.py and adding requirements for sqlalchemy, migrations, and dotenv

Relevant issues 
https://github.com/wuryantoAji/cits5505GroupProject/issues/7

### CODE REVIEW

**Comment by dtdoris** [comment]
SQLite3; structure and logic, reviewed; AGREE to emerge:
        1. Comment
            Pretty clear it is structured completely, and the logic flow is smooth for me. 
        2. Decision
            Agree to emerge it into main branch. 
        3. Recommendation
            Subsequent testing needed after finalization of main Game code.

Only one question: **what is the usage for “score_id”?** 
If we need to rank scores for one game_id, we could just sort “score”, and identify the highest ranks by “game_id, score, user_id”. If there is a “score_id”, how could we manage the sequence number as the value of “score_id” among all users for all games?

**Comment by wuryantoAji** [comment]
so "score_id" in Score table will be used to store the score that a user gets after their attempt on the particular wordle puzzle. when ranking the score for the scoreboard, you will only need to sort the overall score in the User table.

**Comment by SoleilGU** [comment]
The following is needed in the user profile regarding games created by the user themselves: roughly how many times the game needs to have been played (number), comments from players and possibly a rating of the game by everyone. 
Also, would like to discuss if cumulative scores are necessary. I can understand that using cumulative scores for ranking is to encourage players to play multiple times, but I would like to discuss whether it is better to show the cumulative score or the single highest score.

**Comment by wuryantoAji** [comment]
Great suggestion, I think I will add a number of attempts in the score table and number of times the puzzled have been played in the puzzle table.
Regarding the score, I think for ease of implementation we can use the single highest score instead of cumulative score. 
what do you guys think?

**Pull request merged**
