### PR TITLE
Yuxin -- design of pages

### PR DESCRIPTION
**Pull request by SoleilGU**
Some components for the website, the puzzle list page and the leaderboard page share some fundamental components. And the design of puzzle list one and leaderboard one can be seen in our figma, plz check it. 
As for the font, I will upload a pixel font later, but if you guys already have a good pixel font, feel free to upload it.

- [ √ ]  Index Page Design
Screenshot 2024-05-03 233825

- [ √ ]  Leaderboard Page Design
Screenshot 2024-05-07 173641

- [ √ ]  Puzzle List Page Design
Screenshot 2024-05-07 173651

- [ √ ]  Seperate images into different folders
 
Screenshot 2024-05-07 174009

### CODE REVIEW

**Comment by SoleilGU** [comment]
@wuryantoAji @dtdoris @opaskah Let me know your reviews for the design.

**Review by wuryantoAji — APPROVED** [review]
Awesome work Yuxin. I don't have any comments for all of this, let's merge this as soon as possible so that others can also use the asset for their page

**Comment by SoleilGU** [comment]
> Awesome work Yuxin. I don't have any comments for all of this, let's merge this as soon as possible so that others can also use the asset for their page

No problem, I will merge this at 22:00~

**Comment by dtdoris** [comment]
GREAT JOB!! I love the art!!

**Pull request merged**
