### PR TITLE
login page html/css + 404 page

### PR DESCRIPTION
**Pull request by SoleilGU**
**Related Issue:** #1 
Finished static part of login page
image
Going to work on the modal dialog box for login and register, as well as login_register.py

### CODE REVIEW

**Comment by SoleilGU** [comment]
By NOW, **FINISHED**:
1. html / css/ js code for login-register page
Screenshot 2024-05-12 173947

FUNCTIONs: 
· 2 Modal popups for login and signup, when typing in the text frame, the default 'Username' and 'Password' will disappear.
Screenshot 2024-05-12 173954
Screenshot 2024-05-12 174002

· When click on 'guest', the website will jump to puzzle list page.
· Use jQuery to send AJAX Request: if login successfully, it will jump to puzzle list page; elif fail to login, it will send error message; if register successfully, it will close the signup modal and open the login modal; else, it will send an error message.
2. login_register.py : the Flask structure for login and register, not really sure about this part (do I need to add something in model.py?)

Future Improvements: 
**RESPONSIVE LAYOUT**: Responsive change of elements in the page, when the browser's page size changes, the elements have a corresponding change;
Strict authentication - protect from XSS/ SQL inject; 
Request more complex password + reset password functions.

**Review by wuryantoAji — APPROVED** [review]
Great work Yuxin.
No, I don't think you need to add anything to the models.py. Everything should work wonderfully

**Comment by SoleilGU** [comment]
404 page：
Screenshot 2024-05-13 151743

**Review by opaskah — APPROVED** [review]
Good work.

**Comment by dtdoris** [comment]
Beautiful!!

**Pull request merged**
