### PR TITLE
components for game page, as well as some other images

### PR DESCRIPTION
**Pull request by SoleilGU**
These are components for game page, including a game board with a left-side scoreboard, a title board, a comment board, and four text frames for the wordle game. There are some other images (clouds) in 'others' folder, if the background is too empty, you can use these materials on the background, and you can use CSS transform to create a simple cloud floating animation to make the background more dynamic. 
What's more, there is a pixel font zip file, if the font file doesn't work in your html/css, plz tell me.

- [ √ ]  Design of game page (without comment1/ comment2) 
Screenshot 2024-05-08 003419
Screenshot 2024-05-08 003537

- [ √ ]  Pixel Font for all pages

- [ √ ]  Clouds images for cloud animation in 'others' folder 
Screenshot 2024-05-08 003938

### CODE REVIEW

**Comment by SoleilGU** [comment]
The Text frames can be larger in the page, the size shown is too small for the player.
And I will try to finish the keyboard and comment1/comment2 part tmr (Wednesday). 
As for the text color, I recommend that in original and yellow frames, the text color can be dark gray/ black/... , and in right and notin frames, the color can be white or some light color.
And I haven't finished the submit button.
For the design of 'create' page, I need you guys' help. Can you guys please tell me the detail process of players building up the wordle game, 
Screenshot 2024-05-08 005308
This is the basic requirements I know by now, but let me know if your design have changed.

**Comment by SoleilGU** [comment]
@wuryantoAji @dtdoris @opaskah

**Review by wuryantoAji — APPROVED** [review]
Great work Yuxin, for the create game page I think Chuanrui said that the flow is that after the user fills the input for the game, she will need an extra page that says pretty much something like this, "Game has been submitted, here is the link to the game". 
Is this pretty much correct? @dtdoris

**Comment by SoleilGU** [comment]
> Great work Yuxin, for the create game page I think Chuanrui said that the flow is that after the user fills the input for the game, she will need an extra page that says pretty much something like this, "Game has been submitted, here is the link to the game". Is this pretty much correct? @dtdoris

Got it. But I’m not sure whether I have enough time for one more page design, because I’ve already have four tasks: the total design, the login page, the profile page and 404 page… I will really appreciate it if you can choose pop-up windows to meet this requirement or do the design of extra page by yourself @dtdoris . If you decide to do a pop-up windows, you can use the title frame, which is in the ‘game page’ folder, as the frame of the message “successful xxxx”. 
Feel free to inform me if you have any further questions.

**Review by wuryantoAji — CHANGES_REQUESTED** [review]
Apologies I just realized something.... can you move all of the images to the static folder? if you put the images outside the static folder, Flask will not be able to find the asset and will not be able to display it correctly. Thanks in advance

**Comment by SoleilGU** [comment]
> Apologies I just realized something.... can you move all of the images to the static folder? if you put the images outside the static folder, Flask will not be able to find the asset and will not be able to display it correctly. Thanks in advance

No problem. I will finish it before 5pm.

**Pull request merged**
